import platform


PDF 		= 0
ARCHIVE 	= 1
ZOOM 		= 2
VIDEO 		= 3
YOUTUBE 	= 4
SECTION 	= 5
SUBFOLDER 	= 6
supportedTypes = [PDF, ARCHIVE, ZOOM, VIDEO, YOUTUBE, SECTION, SUBFOLDER]


MOODLESIMULATOR = 0
CATEGORYSORTED = 1


COOKIE_EXPIRY_ESTIMATE = 3600	# 1 hour = 60sec*60min


useDriver = True

MODE = MOODLESIMULATOR
#MODE = CATEGORYSORTED

PLATFORM = platform.system()